== Handoverjobs

A Handoverjob is the entity that supports the process around the handover of picked goods towards

* a carrier (in case of deliveries / ship from store)

Handoverjobs must be distinguished from <<Parcels>> as the latter are the physical packages, that are sent, receive tracking information and are delivered to the consumer in the end.
<<Handoverjobs>> on the other side are entities, that aid in the handover process of the physical picking result to the next process step, namely the pickup by a carrier.

=== Lifecycle of Handoverjobs
For now a handoverjob is automatically created whenever a label of a parcel is successfully being created. The current state transitions are

[cols=2,options="header"]
|===

| State | Description

|  OPEN | The parcel label was successfully created (carrier acknowledged the transportation of the connected parcel) & the parcel should be ready to be picked up by the carrier.
|  HANDED_OVER | The parcel was handed over to the carrier / put to the place where the carrier will find it for the actual pickup at a later point in time. The connected parcel will receive further tracking status updates.

|===
