type: environment.insomnia.rest/5.0
schema_version: "5.1"
name: ocff-example-prd
environments:
  name: Base Environment
  meta:
    id: env_base
    isPrivate: false
  data:
    host: "https://{{project_id}}.api.fulfillmenttools.com"
    project_id: "<your-project-here>"
    fft_user: "<your-email-here>"
  subEnvironments:
    - name: private-environment (credentials)
      meta:
        id: env_private_credentials
        isPrivate: true
      data:
        fft_password: "<your-password-here>"
        fft_api_key: "<your-api-key-here>"
