== Tenant
In the fulfillmenttools platform a tenant is another word for our customer - and that happens to be you (once you decided to work with us).
You will be issued with your own independent managed SaaS platform in regards of data segregation, call routing and configuration for your business without having to worry about scalability and security.

The tenant system can be configured and in this section we will present some configurations on a tenant level.

=== Tenant based configurations

The configurations mentioned here are applicable for the whole tenant. In other words: to all your facilities and for all your processes. More detailed configuration on facility level is mentioned in the <<Facilities>> section.

[cols=4,options="header"]
|===

| Name of feature | Description | Default Value | How to activate?

|  Infinite Stock | The platform or, to be more precise, the Distributing Order Management System, can be configured in a way that it assumes infinite stock for the product listings you provide to fulfillmenttools. However, you can still disable single listings for not to be taken into consideration in your Backoffice-Application. | *Disabled* | Please get in contact with us.

|===
