name: build adocs

on:
  push:
    branches:
      - master

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: asciidoctor --backend=html5 -o index.html doc/Readme.adoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get build container
        id: adocbuild
        uses: tonynv/asciidoctor-action@28d076475809567f00d35696db08f8454d70eabb
        with:
          program: "asciidoctor --backend=html5 -o index.html doc/Readme.adoc"

      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./
